# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7003c5d341f23785b40f2f33fb084e64985f5d316b82c2a48117359fa89746cdca1b9d339de422af4eae1b28e60e0897f54a1df4f8ada048d2e7c31f407e487

test:
  secret_key_base: 2a5fae5c976b17ab797e11307519274ab0463f8112070e8fcfc5cb5437091ac055e55448bbb12f36e0def216c89175ec567a165f4a92f1e2c946ae077226155c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
